version: '3'
services:
  web:
    container_name: nginx1
    ports:
      - "8080:80"
    volumes:
      - "vol2:/usr/share/nginx/html"
    image: nginx
    mem_limit: 20m
    cpuset: "0"
volumes:
  vol2: