version: '3'
services:
  web:
    container_name: nginx2
    ports:
      - "8081:80"
    volumes:
      - "/home/alberto/cursos/cursosUdemy/Docker/Docker-compose/Ejemplo1/html:/usr/share/nginx/html"
    image: nginx